export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const LOGOUT__SUCCEEDED = 'LOGOUT__SUCCEEDED';
export const LOGOUT__FAILED = 'LOGOUT__FAILED';

export const VALIDATE_TOKEN_REQUESTED = 'VALIDATE_TOKEN_REQUESTED';
export const VALIDATE_TOKEN__SUCCEEDED = 'VALIDATE_TOKEN__SUCCEEDED';
export const VALIDATE_TOKEN__FAILED = 'VALIDATE_TOKEN__FAILED';