export const DASHBOARD_NAVI_REQUESTED = 'DASHBOARD_NAVI_REQUESTED';
export const DASHBOARD_NAVI__SUCCEEDED = 'DASHBOARD_NAVI__SUCCEEDED';
export const DASHBOARD_NAVI__FAILED = 'DASHBOARD_NAVI__FAILED';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const LOGOUT__SUCCEEDED = 'LOGOUT__SUCCEEDED';
export const LOGOUT__FAILED = 'LOGOUT__FAILED';

export const HTML_FETCH_REQUESTED = 'HTML_FETCH_REQUESTED';
export const HTML_FETCH__SUCCEEDED = 'HTML_FETCH__SUCCEEDED';
export const HTML_FETCH__FAILED = 'HTML_FETCH__FAILED'; 

export const CHANNEL_FETCH_REQUESTED = 'CHANNEL_FETCH_REQUESTED';
export const CHANNEL_FETCH__SUCCEEDED = 'CHANNEL_FETCH__SUCCEEDED';
export const CHANNEL_FETCH__FAILED = 'CHANNEL_FETCH__FAILED';

export const CHANNEL_UPDATE_STATUS_REQUESTED = 'CHANNEL_UPDATE_STATUS_REQUESTED';
export const CHANNEL_UPDATE_STATUS__SUCCEEDED = 'CHANNEL_UPDATE_STATUS__SUCCEEDED';
export const CHANNEL_UPDATE_STATUS__FAILED = 'CHANNEL_UPDATE_STATUS__FAILED';

export const EXPERIENCE_UPDATE_SEARCH_REQUESTED = 'EXPERIENCE_UPDATE_SEARCH_REQUESTED';
export const EXPERIENCE_UPDATE_SEARCH__SUCCEEDED = 'EXPERIENCE_UPDATE_SEARCH__SUCCEEDED';
export const EXPERIENCE_UPDATE_SEARCH__FAILED = 'EXPERIENCE_UPDATE_SEARCH__FAILED';

export const EXPERIENCE_UPDATE_FILTER_REQUESTED = 'EXPERIENCE_UPDATE_FILTER_REQUESTED';
export const EXPERIENCE_UPDATE_FILTER__SUCCEEDED = 'EXPERIENCE_UPDATE_FILTER__SUCCEEDED';
export const EXPERIENCE_UPDATE_FILTER__FAILED = 'EXPERIENCE_UPDATE_FILTER__FAILED';

export const EXPERIENCE_CLEAR_FILTER_REQUESTED = 'EXPERIENCE_CLEAR_FILTER_REQUESTED';
export const EXPERIENCE_CLEAR_FILTER__SUCCEEDED = 'EXPERIENCE_CLEAR_FILTER__SUCCEEDED';
export const EXPERIENCE_CLEAR_FILTER__FAILED = 'EXPERIENCE_CLEAR_FILTER__FAILED';

export const EXPERIENCE_FETCH_REQUESTED = 'EXPERIENCE_FETCH_REQUESTED';
export const EXPERIENCE_FETCH__SUCCEEDED = 'EXPERIENCE_FETCH__SUCCEEDED';
export const EXPERIENCE_FETCH__FAILED = 'EXPERIENCE_FETCH__FAILED'; 

export const EXPERIENCE_FETCH_MORE_REQUESTED = 'EXPERIENCE_FETCH_MORE_REQUESTED';
export const EXPERIENCE_FETCH_MORE__SUCCEEDED = 'EXPERIENCE_FETCH_MORE__SUCCEEDED';
export const EXPERIENCE_FETCH_MORE__FAILED = 'EXPERIENCE_FETCH_MORE__FAILED'; 

export const EXPERIENCE_DELETE_REQUESTED = 'EXPERIENCE_DELETE_REQUESTED';
export const EXPERIENCE_DELETE__SUCCEEDED = 'EXPERIENCE_DELETE__SUCCEEDED';
export const EXPERIENCE_DELETE__FAILED = 'EXPERIENCE_DELETE__FAILED'; 

export const STREAM_CHANNEL_FETCH_REQUESTED = 'STREAM_CHANNEL_FETCH_REQUESTED';
export const STREAM_CHANNEL_FETCH__SUCCEEDED = 'STREAM_CHANNEL_FETCH__SUCCEEDED';
export const STREAM_CHANNEL_FETCH__FAILED = 'STREAM_CHANNEL_FETCH__FAILED';

export const STREAM_CHANNEL_SELECT_REQUESTED = 'STREAM_CHANNEL_SELECT_REQUESTED';
export const STREAM_CHANNEL_SELECT__SUCCEEDED = 'STREAM_CHANNEL_SELECT__SUCCEEDED';
export const STREAM_CHANNEL_SELECT__FAILED = 'STREAM_CHANNEL_SELECT__FAILED';

export const STREAM_CREATE_REQUESTED = 'STREAM_CREATE_REQUESTED';
export const STREAM_CREATE__SUCCEEDED = 'STREAM_CREATE__SUCCEEDED';
export const STREAM_CREATE__FAILED = 'STREAM_CREATE__FAILED';

export const STREAM_REMOVE_REQUESTED = 'STREAM_REMOVE_REQUESTED';
export const STREAM_REMOVE__SUCCEEDED = 'STREAM_REMOVE__SUCCEEDED';
export const STREAM_REMOVE__FAILED = 'STREAM_REMOVE__FAILED';