export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const LOGOUT__SUCCEEDED = 'LOGOUT__SUCCEEDED';
export const LOGOUT__FAILED = 'LOGOUT__FAILED';

export const EXPERIENCE_FETCH_REQUESTED = 'EXPERIENCE_FETCH_REQUESTED';
export const EXPERIENCE_FETCH__SUCCEEDED = 'EXPERIENCE_FETCH__SUCCEEDED';
export const EXPERIENCE_FETCH__FAILED = 'EXPERIENCE_FETCH__FAILED'; 