export const FETCH_GISTS_REQUESTED = 'FETCH_GISTS_REQUESTED';
export const FETCH_GISTS__SUCCEEDED = 'FETCH_GISTS__SUCCEEDED';
export const FETCH_GISTS__FAILED = 'FETCH_GISTS__FAILED';

export const ADD_GIST_REQUESTED = 'ADD_GIST_REQUESTED';
export const ADD_GIST__SUCCEEDED = 'ADD_GIST__SUCCEEDED';
export const ADD_GIST__FAILED = 'ADD_GIST__FAILED';

export const REMOVE_GIST_REQUESTED = 'REMOVE_GIST_REQUESTED';
export const REMOVE_GIST__SUCCEEDED = 'REMOVE_GIST__SUCCEEDED';
export const REMOVE_GIST__FAILED = 'REMOVE_GIST__FAILED';
