export const EXPERIENCE_TYPE_REQUESTED = 'EXPERIENCE_TYPE_REQUESTED';
export const EXPERIENCE_TYPE__SUCCEEDED = 'EXPERIENCE_TYPE__SUCCEEDED';
export const EXPERIENCE_TYPE__FAILED = 'EXPERIENCE_TYPE__FAILED';