export const EXPERIENCE_TYPE_REQUESTED = 'EXPERIENCE_TYPE_REQUESTED';
export const EXPERIENCE_TYPE__SUCCEEDED = 'EXPERIENCE_TYPE__SUCCEEDED';
export const EXPERIENCE_TYPE__FAILED = 'EXPERIENCE_TYPE__FAILED';

export const EXPERIENCE_TYPE_UPDATE_REQUESTED = 'EXPERIENCE_TYPE_UPDATE_REQUESTED';
export const EXPERIENCE_TYPE_UPDATE__SUCCEEDED = 'EXPERIENCE_TYPE_UPDATE__SUCCEEDED';
export const EXPERIENCE_TYPE_UPDATE__FAILED = 'EXPERIENCE_TYPE_UPDATE__FAILED';

export const EXPERIENCE_INDEX_UPDATE_REQUESTED = 'EXPERIENCE_INDEX_UPDATE_REQUESTED';
export const EXPERIENCE_INDEX_UPDATE__SUCCEEDED = 'EXPERIENCE_INDEX_UPDATE__SUCCEEDED';
export const EXPERIENCE_INDEX_UPDATE__FAILED = 'EXPERIENCE_INDEX_UPDATE__FAILED';