export const CHANNEL_TYPE_REQUESTED = 'CHANNEL_TYPE_REQUESTED';
export const CHANNEL_TYPE__SUCCEEDED = 'CHANNEL_TYPE__SUCCEEDED';
export const CHANNEL_TYPE__FAILED = 'CHANNEL_TYPE__FAILED';

export const CHANNEL_TYPE_UPDATE_REQUESTED = 'CHANNEL_TYPE_UPDATE_REQUESTED';
export const CHANNEL_TYPE_UPDATE__SUCCEEDED = 'CHANNEL_TYPE_UPDATE__SUCCEEDED';
export const CHANNEL_TYPE_UPDATE__FAILED = 'CHANNEL_TYPE_UPDATE__FAILED';