export const VALIDATE_TOKEN_REQUESTED = 'VALIDATE_TOKEN_REQUESTED';
export const VALIDATE_TOKEN__SUCCEEDED = 'VALIDATE_TOKEN__SUCCEEDED';
export const VALIDATE_TOKEN__FAILED = 'VALIDATE_TOKEN__FAILED';

export const NAVIGATE_HISTORY_REQUESTED = 'NAVIGATE_HISTORY_REQUESTED';
export const NAVIGATE_HISTORY__SUCCEEDED = 'NAVIGATE_HISTORY__SUCCEEDED';
export const NAVIGATE_HISTORY__FAILED = 'NAVIGATE_HISTORY__FAILED';

export const ALERT_REQUESTED = 'ALERT_REQUESTED';
export const ALERT__SUCCEEDED = 'ALERT__SUCCEEDED';
export const ALERT__FAILED = 'ALERT__FAILED';